{"lang": "Python"}
{"lang": "Python"}
{"lang": "Python"}
{"lang": "C"}
{"lang": "Python"}
{"lang": "Python"}
{"lang": "Python"}
{"lang": "Python"}
{"lang": "C"}
{"lang": "Python"}
{"lang": "C++"}
{"lang": "C++"}
{"lang": "Python"}
{"lang": "Python"}
{"lang": "C++"}
{"lang": "Python"}
{"lang": "Python"}
